import spekpy as sp
import numpy as np
import sys
import os
# ====================================================================
# --- SOURCE CONFIGURATION BLOCKS (THE "STRUCTS") ---
# Contains all parameters AND the final output filename.
# ====================================================================
SOURCE_CONFIGS = [
    {
        'NAME': 'test30kv_rh_be_spekpy',
        'OUTPUT_FILE': 'spectrum/test30kv_rh_be_spekpy.spc',
        'KVP': 30.0,
        'TARG_MATERIAL': 'W',
        'ANODE_ANGLE_DEG': 16.0,
        'PHYSICS': 'casim',
        'FILTER_1': ('Be', 1.0), # (Material, Thickness in mm)
        'FILTER_2': ('Rh', 0.05), # (Material, Thickness in mm)
    },
    {
        'NAME': '120kV_Al150um_Brass60um',
        'OUTPUT_FILE': 'spectrum/120kV_Al150um_Brass60um.spc',
        'KVP': 120.0,
        'TARG_MATERIAL': 'W',
        'ANODE_ANGLE_DEG': 16.0,
        'PHYSICS': 'casim',
        'FILTER_1': ('Al', 1.5), 
        'FILTER_2': ('Copper Alloy (Cartridge Brass)', 0.6), # (Material, Thickness in mm)
    },
    {
        'NAME': '80kV_Al350um',
        'OUTPUT_FILE': 'spectrum/80kV_Al350um.spc',
        'KVP': 80.0,
        'TARG_MATERIAL': 'W',
        'ANODE_ANGLE_DEG': 16.0,
        'PHYSICS': 'casim',
        'FILTER_1': ('Al', 3.5), 
        'FILTER_2': (None, 0.0), # (Material, Thickness in mm)
    },
    # Add more source configurations here as needed
]
# --- MC-GPU Output Parameters (Fixed from your previous request) ---
START_KEV = 5    # Starting energy of the first bin lower edge (in keV) da 5keV
STEP_KEV = 0.5     # Energy step/width of the bins (in keV)
NUM_OUTPUT_BINS = 230 # The required total number of bins for the MC-GPU input a 120keV
# ------------------------------------------------------------------


def generate_and_export_spectrum(source_config):
    """
    Generates the spectrum for a single source configuration, formats it, 
    and exports the data to the file specified in the config.
    """
    
    # Unpack the configuration dictionary
    NAME = source_config['NAME']
    OUTPUT_FILE = source_config['OUTPUT_FILE']
    KVP = source_config['KVP']
    TARG_MATERIAL = source_config['TARG_MATERIAL']
    ANODE_ANGLE_DEG = source_config['ANODE_ANGLE_DEG']
    PHYSICS = source_config['PHYSICS']
    FILTER_1_MAT, FILTER_1_THICKNESS = source_config['FILTER_1']
    FILTER_2_MAT, FILTER_2_THICKNESS = source_config['FILTER_2']
    
    # --- Generation and Formatting Logic ---

    print(f"\n--- Processing Source: {NAME} ---")
    print(f"Generating {TARG_MATERIAL} spectrum at {KVP} kVp...")
    
    # 1. Initialize SpekPy instance
    s = sp.Spek(kvp=KVP, targ=TARG_MATERIAL, th=ANODE_ANGLE_DEG, dk=STEP_KEV, shift=0.5, physics=PHYSICS)
    
    # 2. Apply Stacked Filtration
    if FILTER_1_MAT is not None:
        s.filter(FILTER_1_MAT, FILTER_1_THICKNESS)
    if FILTER_2_MAT is not None:
        s.filter(FILTER_2_MAT, FILTER_2_THICKNESS)
    
    # 4. Extract Data
    # get_spectrum() returns (energies, fluence), where:
    # energies (E): lower edge of the energy bins (in keV)
    # fluence (P): photons / (area * dE) e.g., photons/(mm^2*keV) per unit exposure
    
    #Extract Data using get_spectrum()
    # It returns a tuple: (energies_keV, fluence_per_keV)
    energies_keV, fluence_per_keV = s.get_spectrum(diff=False)
    
        
    # 5. Create Energy Grid: Bin Centers
    # First bin (0.5-1.0 keV) center is 0.75 keV.
    
    # Create array of 256 bin centers (in keV)
    final_fluence = []
    energies_eV = []
    for e, p in zip(energies_keV, fluence_per_keV):
        if e >= START_KEV and e < (START_KEV + NUM_OUTPUT_BINS * STEP_KEV):
            final_fluence.append(p)
            energies_eV.append(e * 1e3)  # Convert keV to eV for output


    # 6. Write Output File
    N = len(final_fluence)
    print(f"Writing output to {OUTPUT_FILE} with {N} bins...")
    
    with open(OUTPUT_FILE, 'w') as f:
        f.write('# Generated by SpekPy Script for MC-GPU (NORMALIZED, 256 BINS)\n')
        f.write(f'# Spectrum normalized to 1 mAs (per mAs).\n')
        f.write(f'# Max Energy (Upper Edge): {(energies_eV[-1]/1e3 + STEP_KEV):.2f} keV.\n')
        f.write('# Energy [eV]      Num. photons/(mm^2*keV) [Normalized Fluence]\n')
        
        for e, p in zip(energies_eV, final_fluence):
            f.write(f"{e:.6e}   {p:.6e}\n")
            
        # Write termination marker (Upper edge of the last bin)
        f.write(f"{(energies_eV[-1]/1e3 + STEP_KEV) * 1e3:.6e}   {-1.0:.6e}\n")
        
    print(f'\n*** Conversion Complete ***')
    print(f'Wrote {N} bins to {OUTPUT_FILE}')
    print(f'First bin center: {energies_eV[0]/1e3:.2f} keV')

if __name__ == '__main__':
    try:
        # Loop through all defined source configurations
        for config in SOURCE_CONFIGS:
            generate_and_export_spectrum(config)
            
    except Exception as e:
        print(f"\nFATAL ERROR: A spectrum generation failed.", file=sys.stderr)
        print(f"Details: {e}", file=sys.stderr)
        sys.exit(1)